kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: luigi
  labels:
    app: phenomenal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phenomenal
      task: luigi
  template:
    metadata:
      labels:
        app: phenomenal
        task: luigi
    spec:
      containers:
      - name: luigi
        image: farmbio/luigid
        ports:
          - containerPort: 8082
        resources:
          requests:
            memory: 1G
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: luigi
spec:
  ports:
  - name: http
    targetPort: 8082
    port: 8082
  selector:
    app: phenomenal
    task: luigi
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: luigi-ingress
spec:
  rules:
  - host: luigi.jupydemo.phenomenal.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: luigi
          servicePort: http

